### Guinzburg Nathanael 305091357

### Import packages

In [5]:
import numpy as np
import timeit

Q1) a) Implement a function named `mat_mul`, which takes two matrices $A$ and $B$ as parameters and returns the result of matrix multiplication $C = A * B$.  
Your function should assert that the number of dimensions of each of the two matrices $A$ and $B$ is exactly 2.  
In addition, your function should assert that $A$ number of columns is equal to $B$ number of rows, in order for the matrix multiplication operation to be well defined.  
The function should take a third parameter `method` of type `str`, which can take on one of only three values:
- 'for loop'
- 'sum product'
- 'numpy dot'  
  
Let the matrices shapes be $A_{mxn}$, $B_{nxp}$, and $C_{mxp}$.  
In the first **'for loop'** method, you will have three nested for loops $i \in \{0, m-1\}$, $j \in \{0, p-1\}$, and $k \in \{0, n-1\}$, such that $C(i,j) = \sum_{k=1}^n{A(i,k) \cdot B(k,j)}$.  
In the second **'sum product'** method you will get rid of the $k$ for loop, and implement the sum of products with the numpy functions `np.sum` and `np.multiply`.  
Finally, in the third **'numpy dot'** method you will simply call numpy's `np.dot` function.

In [6]:
def mat_mul(A, B, method):
    
    # assert that {A} {B} dimensions are equal
    if not A.ndim == B.ndim == 2:
        return 0

    row_A, col_A = np.shape(A)
    row_B, col_B = np.shape(B)
    C = np.zeros((row_A, col_B))
    
    if method == 'for loop':
        # iterate through rows of {A}
        for i in range(row_A):
            # iterate through columns of {B}
            for j in range(col_B):
                # iterate through rows of {B}
                for k in range(row_B):
                    C[i][j] += A[i][k] * B[k][j]
    elif method == 'sum product':
        # iterate through rows of {A}
        for i in range(row_A):
            # iterate through columns of {B}
            for j in range(col_B):
                C[i][j] = np.sum(np.multiply(A[i, :], B[:, j]))
    elif method == 'numpy dot':
        C = A.dot(B)
    
    return C


b) Test the correctness of your function on small matrices:  
if your implementation is correct then you should obtain the same results, using the three different methods.  
Create a matrix A of shape(2,4) filled with numbers from 1 to 8.  
Create a matrix B of shape(4,2) filled with numbers from 9 to 16.  
Call the `mat_mul` function 3 times, each time using a different method.  
Print the input matrices $A$ and $B$, and the resulting matrices $C1$, $C2$, and $C3$.

In [7]:
# Create a matrix A of shape(2,4) filled with numbers from 1 to 8
A = np.arange(1,9).reshape(2,4)
# Create a matrix B of shape(4,2) filled with numbers from 9 to 16
B = np.arange(9,17).reshape(4,2)
# Call the mat_mul function using the method 'for loop' and store the result in C1.
C1 = mat_mul(A, B, 'for loop')
# Call the mat_mul function using the method 'sum product' and store the result in C2.
C2 = mat_mul(A, B, 'sum product')
# Call the mat_mul function using the method 'numpy dot' and store the result in C3.
C3 = mat_mul(A, B, 'numpy dot')

print('A =\n', A)
print('B =\n', B)
print('C (for loop) =\n', C1)
print('C (sum product) =\n', C2)
print('C (numpy.dot) =\n', C3)

A =
 [[1 2 3 4]
 [5 6 7 8]]
B =
 [[ 9 10]
 [11 12]
 [13 14]
 [15 16]]
C (for loop) =
 [[130. 140.]
 [322. 348.]]
C (sum product) =
 [[130. 140.]
 [322. 348.]]
C (numpy.dot) =
 [[130 140]
 [322 348]]


c) Now compare the performance or running time of your function's three different methods.  
For this prurpose you will generate random square matrices $A_{nxn}$ and $B_{nxn}$, with increasing size $n$: $n = [10, 50, ..., 100]$.  
Read the documentation about the magic fuction `%timeit`, and inside the loop over $n$ measure and compare the running-times of the 3 different methods for increasing matrix size $n$.  
Describe and explain your results.  
Note: the output you obtain does not have to perfectly match the ouput below.

In [4]:
np.random.seed(123)
for n in [10, 50, 100]:
    
    print('\nn =', n)
    
    # create matrix A of shape (n,n) with numbers randomly sampled from a normal distribution
    A = np.random.normal(loc=0, scale=1, size=(n,n))
   
    # create matrix B of shape (n,n) with numbers randomly sampled from a normal distribution
    B = np.random.normal(loc=0, scale=1, size=(n,n))
        
    print('for loop:')
    # measure the running-time of mat_mul function with 'for loop' method, using the %timeit function
    %timeit mat_mul(A, B, 'for loop')
    
    print('sum product:')
    # measure the running-time of mat_mul function with 'sum product' method, using the %timeit function
    %timeit mat_mul(A, B, 'sum product')

    print('numpy dot:')
    # measure the running-time of mat_mul function with 'numpy dot' method, using the %timeit function
    %timeit mat_mul(A, B, 'numpy dot')
    


n = 10
for loop:
1.65 ms ± 42.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
sum product:
2.1 ms ± 13.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
numpy dot:
9 µs ± 500 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

n = 50
for loop:
203 ms ± 9.95 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
sum product:
57.2 ms ± 3.44 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
numpy dot:
213 µs ± 53.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

n = 100
for loop:
1.63 s ± 69.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
sum product:
218 ms ± 856 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
numpy dot:
375 µs ± 25.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Q2) a) Implement a function named `describe_num`, which takes a 1D numpy array $x$, and returns a dictionary $d$ of decriptive statistics: **count**, **min**, **mean**, **std** (standard deviation), **25%**, **50%** (same as median), and **75%** percentile, and **max**, using the appropriate `numpy` functions / methods. 

In [50]:
def describe_num(x):
    return {
        "count": len(x),
        "min": np.amin(x),
        "mean": np.mean(x),
        "std": np.std(x),
        "25%": np.percentile(x, 25),
        "50%": np.percentile(x, 50),
        "75%": np.percentile(x, 75),
        "max": np.amax(x)
    }


b) Test the correctness of your function

In [51]:
x = np.arange(0, 101) ** 2
d = describe_num(x)
[print(f'{key}\t{value}') for key, value in d.items()];

count	101
min	0
mean	3350.0
std	3012.943743251772
25%	625.0
50%	2500.0
75%	5625.0
max	10000


c) Implement a function named `describe_cat`, which takes a 1D numpy array $x$ of categorical values, and returns a dictionary $d$ of decriptive statistics: **count**, **unique**, **top**, and **freq**, using the appropriate `numpy` functions / methods.   
**unique** is the number of unique categories.  
**top** is the most frequent category.  
**freq** is the number of occurrences of the most frequent category.

In [199]:
def describe_cat(x):
    unique, pos = np.unique(x, return_inverse=True)
    return {
        "count": len(x),
        "unique": unique,
        "top": unique[np.bincount(pos).argmax()],
        "freq": np.amax(np.bincount(pos))
    }


d) Test the correctness of your function

In [200]:
x = np.array(['A', 'B', 'B', 'C', 'A', 'A', 'A', 'C', 'A', 'C'])
# call the function describe_cat with argument x
res = describe_cat(x)
# print the result
print(res)

{'count': 10, 'unique': array(['A', 'B', 'C'], dtype='<U1'), 'top': 'A', 'freq': 5}
